name: Jethro Jones DOT com!
url: http://jethrojones.com
markdown: redcarpet
pygments: true

#RSS
description: Awesome RSS feed for jethrojones.com
author: Jethro Jones
copyright: (C) Jethro Jones 2014
rss_name: feed.xml


# Categories
category_dir: categories